# Generated by Django 4.1.7 on 2023-02-25 07:45

import common.models
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('daily_cost', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Daily cost')),
                ('place_count', models.PositiveIntegerField(verbose_name='Place count')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start')),
                ('finish', models.DateTimeField(default=common.models.tomorrow_date, verbose_name='Finish')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booked by')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room', verbose_name='Rooms')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('finish__gt', models.F('start'))), name='check_finish', violation_error_message='Booking finish cant be before booking start.'),
        ),
    ]
