version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
       bash -c "poetry run python src/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - envs/.env

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py migrate"
    profiles:
      - migrate
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - envs/.env

  collectstatic:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py collectstatic --noinput --clear"
    profiles:
      - collectstatic
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - envs/.env

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_pass
      - POSTGRES_DB=empha_booking


volumes:
  postgres_data:
